import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider';
import { ThemeProvider } from '@mui/material';
import '../styles/reactCalendar.css';
import UserContextAPI from './context/UserContextAPI';
import { theme } from '@/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Supreme Sprouts Ltd.',
  description: 'Generated by create next app',
  generator: 'Next.js',
  keywords: ['supreme sprouts', 'Supreme Sprouts Ltd.', 'SupremeSprouts'],
  authors: [
    { name: 'Bin Mai' },
    {
      name: 'Mai Thien Phuc',
      url: 'https://maithienphuc.vercel.app',
    },
  ],
  icons: {
    icon: ['/logo-48x48.png'],
    apple: ['/logo-144.png'],
    shortcut: ['/logo-144.png'],
  },
  manifest: '/manifest.json',
};

export const viewport = {
  'minimum-scale': '1',
  'initial-scale': '1',
  width: 'device-width',
  'shrink-to-fit': 'no',
  'viewport-fit': 'cover',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body id="root" className={inter.className}>
        <ThemeProvider theme={theme}>
          <Providers>
            <UserContextAPI>{children}</UserContextAPI>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
