export const sheetStructure: Array<string | number> = [
  'DELIVERY DATE',
  'BEANSPROUTS 10 LBS',
  'BEANSPROUTS 5 LBS',
  'BEANSPROUTS 24 x 1 LB',
  'BEANSPROUTS 1x5',
  'SOYA SPROUTS 10 LBS',
  'SOYA SPROUTS 5 LBS',
  'SOYA SPROUTS 24 x 1 LB',
  'BASIL',
  'JUMBO EGGS',
  'LIQUID EGGS',
  'CUCCUMBER',
  'TOMATO',
  'LIMES',
];
