export const sheetStructure: Array<string | number> = [
  'DATE',
  'BEANSPROUT 10 LBS',
  'BEANSPROUT 5 LBS',
  'BEANSPROUTS 24 x 1 LB',
  'BEANSPROUT 1x5',
  'SOYA SPROUTS 10 LBS',
  'SOYA SPROUTS 5 LBS',
  'SOYA SPROUTS 24 x 1 LB',
  'BASIL',
  'JUMBO EGGS',
  'LIQUID EGG',
  'CUCCUMBER',
  'TOMATO',
  'LIMES',
  'NOTE',
];
