
import { API_URL } from "../../app/utils/enum";
// import { getAuthToken, loginAdminBeforeAll } from "../setUpAuth";

// loginAdminBeforeAll();


describe("Order", () => {
    test('It should returns object of order', async () => {
        try {
            const response = await fetch(`http://localhost:3000/${API_URL.IMPORT_SHEETS}`, {
                method: 'POST',
                headers: { 
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${process.env.TEST_ADMIN_TOKEN}`, 
                },
                body: JSON.stringify({
                    deliveryDate: '2024/01/01',
                    note: 'JEST TEST',
                    items: [
                    {
                    id: 1413,
                    name: 'BEAN 10 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 12,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 18,
                    inventoryUnitId: 2,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 2,
                    totalPrice: 24
                    },
                    {
                    id: 1639,
                    name: 'BEAN 5 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 6,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 19,
                    inventoryUnitId: 3,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 1,
                    totalPrice: 6
                    },
                    {
                    id: 1640,
                    name: 'BASIL',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 7.75,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 51,
                    inventoryUnitId: 26,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1886,
                    name: 'SOYA 10 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 11,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 70,
                    inventoryUnitId: 39,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1888,
                    name: 'SOYA 5 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 5.5,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 71,
                    inventoryUnitId: 40,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1889,
                    name: 'LIME NO. 1',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 48,
                    prevPrice: 52,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 43,
                    inventoryUnitId: 16,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1890,
                    name: 'LIME NO. 2',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 38,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 77,
                    inventoryUnitId: 51,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1891,
                    name: 'TRADITIONAL TOFU',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 29.75,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 52,
                    inventoryUnitId: 27,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1894,
                    name: 'OG CHINESE PUFF',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 32.75,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 54,
                    inventoryUnitId: 29,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1896,
                    name: 'FRIED TOFU',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 31,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 50,
                    inventoryUnitId: 94,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1897,
                    name: 'FIRM TOFU',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 34.75,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 79,
                    inventoryUnitId: 54,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1898,
                    name: 'MEDIUM FIRM TOFU',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 28.75,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 53,
                    inventoryUnitId: 28,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1899,
                    name: 'JUMBO EGG',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 49.99,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 65,
                    inventoryUnitId: 37,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1900,
                    name: 'LARGE EGG',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 63.99,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 49,
                    inventoryUnitId: 23,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1901,
                    name: 'XL EGG',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 64.99,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: false,
                    inventoryItemId: 86,
                    inventoryUnitId: 60,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 1902,
                    name: 'LIQUID EGG 33 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 92,
                    prevPrice: 99,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 17,
                    inventoryUnitId: 1,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 1,
                    totalPrice: 92
                    },
                    {
                    id: 1903,
                    name: 'EGGPLANTS 30 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 50,
                    prevPrice: 60,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 64,
                    inventoryUnitId: 34,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2068,
                    name: 'DAIKON 40 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 25,
                    prevPrice: 29,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 72,
                    inventoryUnitId: 41,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2069,
                    name: 'BROCCOLI 20 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 38,
                    prevPrice: 45,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 46,
                    inventoryUnitId: 19,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2237,
                    name: 'WHITE ONION 50 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 22,
                    prevPrice: 23,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 42,
                    inventoryUnitId: 14,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2332,
                    name: 'USA GREEN CABBAGE',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 0,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: false,
                    inventoryItemId: 88,
                    inventoryUnitId: 75,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2340,
                    name: 'LEUCOCASIA / BAC HA 20 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 110,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 87,
                    inventoryUnitId: 63,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2357,
                    name: 'LEUCOCASIA / BAC HA 30 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 165,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 93,
                    inventoryUnitId: 65,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2400,
                    name: 'TARO',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 54,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 76,
                    inventoryUnitId: 47,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2857,
                    name: 'WHITE MUSHROOM',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 30,
                    prevPrice: 30.25,
                    isShowDiscount: true,
                    availability: true,
                    inventoryItemId: 25,
                    inventoryUnitId: 9,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2858,
                    name: 'NO. 1 OYSTER MUSHROOM 5 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 31,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 73,
                    inventoryUnitId: 44,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2859,
                    name: 'NO. 2 OYSTER MUSHROOM 5 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 19,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 41,
                    inventoryUnitId: 12,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2911,
                    name: 'KING OYSTER',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 36.99,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 83,
                    inventoryUnitId: 57,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2912,
                    name: 'SHIITAKE',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 38,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 84,
                    inventoryUnitId: 58,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2913,
                    name: 'FRESH RICE NOODLE 1 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 2,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 60,
                    inventoryUnitId: 33,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2914,
                    name: 'BANH PHO SINCERE 30 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 44,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 40,
                    inventoryUnitId: 11,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2915,
                    name: 'WONTON NOODLE 1 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 5.5,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 45,
                    inventoryUnitId: 18,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 2916,
                    name: 'CHOW MEIN 10 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 24.5,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 85,
                    inventoryUnitId: 59,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 3015,
                    name: 'ORGANIC GINGER 30 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 60,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: false,
                    inventoryItemId: 56,
                    inventoryUnitId: 32,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 3054,
                    name: 'NO. 2 BELL PEPPER 25 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 25,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 81,
                    inventoryUnitId: 56,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 3056,
                    name: 'PEELED GARLIC 5 LB',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 11.5,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 103,
                    inventoryUnitId: 68,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    },
                    {
                    id: 3082,
                    name: 'JUMBO CARROT',
                    categoryId: 243,
                    subCategoryId: null,
                    price: 19,
                    prevPrice: null,
                    isShowDiscount: null,
                    availability: true,
                    inventoryItemId: 47,
                    inventoryUnitId: 22,
                    inventoryItem: [Object],
                    inventoryUnit: [Object],
                    quantity: 0,
                    totalPrice: 0
                    }
                    ],
                    createdAt: '12:28:42 2024-12-18',
                    isCheckUnavailableRange: true,
                    createdBy: 'admin',
                    isForceOrder: false
                }),
            });
    
            const data = await response.json();
            console.log(response);
            console.log(data)
            if (response.status !== 200) {
                throw new Error('Failed to create order: ' + response);
            }
    
            // console.log(response?.data);
            // const data = await response.json();
    
            expect(data.data).toEqual({
                id: expect.any(Number),
                deliveryDate: '12/19/2024',
                note: 'PHUC TEST',
                createdAt: '12:28:42 2024-12-18',
                items: [],
                createdBy: 'admin',
            });
        } catch (error: any) {
            console.log(error)
            console.log('Fail to create order: ');
        }
    });
});